# following the convention of `javac`, `swiftc`, etc
cppc:
	# e.g. `make cppc f=hello`... MUST explicitly include the `f=` and must NOT append `.cpp`!
	clang++ -std=gnu++2a -Wall "$f.cpp" -o "$f.exe"
